app_name: tgbot
app_version: 1.0.0

pyrogram:
  plugin_dir: "bot/plugins"
  alt_port: true 
  use_mongodb_for_session: true

commands:
   prefix: ["/", "."]
   case_sensitive: false
   
translation:
   dir: "bot/translation"
   default_language: "en"

logging:
    loggers:
        root, tgbot:
          level: "INFO"   
          handlers: ["telegram", "file"]
        pyrogram:
          level: "WARNING"
        pyrogram.parser.html, pyrogram.session.session:
          level: "ERROR"
    handlers:
      telegram:
        chat: -1002233681213
        thread: 2
        chunk: 4000
      file:
        path: "logs/bot.log"
        maxSize: "1 MB" 
        backupCount: 5

groups:
  admin: [1775541139, 1520625615, 1809735866]
  tester: [ 2023698054 ]

subscriptions:
- name: "free"
  data:
    limits:
      max_mails: 3  
- name: "premium"
  data:
    prices: 
      - price: "100,xtr"
        validity: "1,month"
      - price: "200,xtr"
        validity: "3,month"

    limits:
      max_mails: 10
      custom_domains: true
      send: true
      
user_check:
  accept_tc: true
  ban: true
  force_sub:
      chats: 
         - "@theostrich"
  antiflood:
      message_interval: 5
      message_count: 5
  exclude:
   groups: ["admin"]
   subscription: ["premium"]

broadcast:
  users: all    #no. of users to send the message to
  mode: forward #available options: forward, copy

links:
  channel_url: "t.me/theostrich"
  group_url  : "t.me/ostrichdiscussion"
  donation_url: "https://paypal.me/donateostrich"
  repo_url: "https://github.com/RabbitFored/mailable"

extras:
  # add your own extras here


  #if true, port 5222 will be used to connect to Telegram.
  #  test_mode: false            #connect to test servers 
  #  use_ipv6: false
  #  in_memory_session: false    #defaults to true when using session_string
  #  proxy:
  #    scheme: socks5   # "socks4", "socks5" and "http" are supported
  #    hostname: 11.22.33.44
  #    port: 1234

# {'CRITICAL': 50, 'FATAL': 50, 'ERROR': 40, 'WARN': 30, 'WARNING': 30, 'INFO': 20, 'DEBUG': 10, 'NOTSET': 0}